MCF_SCALE_FACTOR = 10000
MILP_SCALE_FACTOR = 1000
OSRM_BATCH_SIZE = 150
ALPHA_VALUE_CONCAVE_HULL_CONCAVITY = 1.0
DISPERSED_CLIENTS_SUBSET_SIZE = 150
OSRM_SERVER_ADDRESS = "http://router.project-osrm.org"